version: '3'
services:
  db:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=1234"
      - "MYSQL_DATABASE=myapi"
      - "MYSQL_ROOT_HOST=%"
    networks:
      - default
      - mynet
  app:
    build: .
    environment:
      - PORT=8088
    ports:
      - "8088:8088"
    depends_on:
      - db
    networks:
      - default
      - mynet
    restart: always

networks:
  mynet:
    driver: bridge