version: '3'
services:
  db:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=1234"
      - "MYSQL_DATABASE=myapi"
      - "MYSQL_ROOT_HOST=%"

  app:
    build: .
    environment:
      - PORT=8090
    env_file:
      - .env
    ports:
      - "8090:8090"
    depends_on:
      - db
    restart: always